/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-26 at 19:15:37 UTC 
 * Modify at your own risk.
 */

package com.appspot.navestockcc_002.navestockccapi.model;

/**
 * Model definition for Fixture.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the navestockccapi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Fixture extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fixtureStatus;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String groundAddress1;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String groundAddress2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String groundAddressCounty;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String groundAddressTown;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String groundName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String groundPostCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String homeOrAway;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer idGround;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer idWinningTeam;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime matchDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer matchId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String matchStartTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String matchType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer navestockRuns;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer navestockTeamId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String navestockTeamName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer navestockWickets;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer oppositionRuns;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer oppositionTeamId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String oppositionTeamName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer oppositionWickets;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String resultDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String winningTeamName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFixtureStatus() {
    return fixtureStatus;
  }

  /**
   * @param fixtureStatus fixtureStatus or {@code null} for none
   */
  public Fixture setFixtureStatus(java.lang.String fixtureStatus) {
    this.fixtureStatus = fixtureStatus;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroundAddress1() {
    return groundAddress1;
  }

  /**
   * @param groundAddress1 groundAddress1 or {@code null} for none
   */
  public Fixture setGroundAddress1(java.lang.String groundAddress1) {
    this.groundAddress1 = groundAddress1;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroundAddress2() {
    return groundAddress2;
  }

  /**
   * @param groundAddress2 groundAddress2 or {@code null} for none
   */
  public Fixture setGroundAddress2(java.lang.String groundAddress2) {
    this.groundAddress2 = groundAddress2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroundAddressCounty() {
    return groundAddressCounty;
  }

  /**
   * @param groundAddressCounty groundAddressCounty or {@code null} for none
   */
  public Fixture setGroundAddressCounty(java.lang.String groundAddressCounty) {
    this.groundAddressCounty = groundAddressCounty;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroundAddressTown() {
    return groundAddressTown;
  }

  /**
   * @param groundAddressTown groundAddressTown or {@code null} for none
   */
  public Fixture setGroundAddressTown(java.lang.String groundAddressTown) {
    this.groundAddressTown = groundAddressTown;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroundName() {
    return groundName;
  }

  /**
   * @param groundName groundName or {@code null} for none
   */
  public Fixture setGroundName(java.lang.String groundName) {
    this.groundName = groundName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroundPostCode() {
    return groundPostCode;
  }

  /**
   * @param groundPostCode groundPostCode or {@code null} for none
   */
  public Fixture setGroundPostCode(java.lang.String groundPostCode) {
    this.groundPostCode = groundPostCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getHomeOrAway() {
    return homeOrAway;
  }

  /**
   * @param homeOrAway homeOrAway or {@code null} for none
   */
  public Fixture setHomeOrAway(java.lang.String homeOrAway) {
    this.homeOrAway = homeOrAway;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIdGround() {
    return idGround;
  }

  /**
   * @param idGround idGround or {@code null} for none
   */
  public Fixture setIdGround(java.lang.Integer idGround) {
    this.idGround = idGround;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIdWinningTeam() {
    return idWinningTeam;
  }

  /**
   * @param idWinningTeam idWinningTeam or {@code null} for none
   */
  public Fixture setIdWinningTeam(java.lang.Integer idWinningTeam) {
    this.idWinningTeam = idWinningTeam;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getMatchDate() {
    return matchDate;
  }

  /**
   * @param matchDate matchDate or {@code null} for none
   */
  public Fixture setMatchDate(com.google.api.client.util.DateTime matchDate) {
    this.matchDate = matchDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMatchId() {
    return matchId;
  }

  /**
   * @param matchId matchId or {@code null} for none
   */
  public Fixture setMatchId(java.lang.Integer matchId) {
    this.matchId = matchId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMatchStartTime() {
    return matchStartTime;
  }

  /**
   * @param matchStartTime matchStartTime or {@code null} for none
   */
  public Fixture setMatchStartTime(java.lang.String matchStartTime) {
    this.matchStartTime = matchStartTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMatchType() {
    return matchType;
  }

  /**
   * @param matchType matchType or {@code null} for none
   */
  public Fixture setMatchType(java.lang.String matchType) {
    this.matchType = matchType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNavestockRuns() {
    return navestockRuns;
  }

  /**
   * @param navestockRuns navestockRuns or {@code null} for none
   */
  public Fixture setNavestockRuns(java.lang.Integer navestockRuns) {
    this.navestockRuns = navestockRuns;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNavestockTeamId() {
    return navestockTeamId;
  }

  /**
   * @param navestockTeamId navestockTeamId or {@code null} for none
   */
  public Fixture setNavestockTeamId(java.lang.Integer navestockTeamId) {
    this.navestockTeamId = navestockTeamId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNavestockTeamName() {
    return navestockTeamName;
  }

  /**
   * @param navestockTeamName navestockTeamName or {@code null} for none
   */
  public Fixture setNavestockTeamName(java.lang.String navestockTeamName) {
    this.navestockTeamName = navestockTeamName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNavestockWickets() {
    return navestockWickets;
  }

  /**
   * @param navestockWickets navestockWickets or {@code null} for none
   */
  public Fixture setNavestockWickets(java.lang.Integer navestockWickets) {
    this.navestockWickets = navestockWickets;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getOppositionRuns() {
    return oppositionRuns;
  }

  /**
   * @param oppositionRuns oppositionRuns or {@code null} for none
   */
  public Fixture setOppositionRuns(java.lang.Integer oppositionRuns) {
    this.oppositionRuns = oppositionRuns;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getOppositionTeamId() {
    return oppositionTeamId;
  }

  /**
   * @param oppositionTeamId oppositionTeamId or {@code null} for none
   */
  public Fixture setOppositionTeamId(java.lang.Integer oppositionTeamId) {
    this.oppositionTeamId = oppositionTeamId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOppositionTeamName() {
    return oppositionTeamName;
  }

  /**
   * @param oppositionTeamName oppositionTeamName or {@code null} for none
   */
  public Fixture setOppositionTeamName(java.lang.String oppositionTeamName) {
    this.oppositionTeamName = oppositionTeamName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getOppositionWickets() {
    return oppositionWickets;
  }

  /**
   * @param oppositionWickets oppositionWickets or {@code null} for none
   */
  public Fixture setOppositionWickets(java.lang.Integer oppositionWickets) {
    this.oppositionWickets = oppositionWickets;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getResultDescription() {
    return resultDescription;
  }

  /**
   * @param resultDescription resultDescription or {@code null} for none
   */
  public Fixture setResultDescription(java.lang.String resultDescription) {
    this.resultDescription = resultDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWinningTeamName() {
    return winningTeamName;
  }

  /**
   * @param winningTeamName winningTeamName or {@code null} for none
   */
  public Fixture setWinningTeamName(java.lang.String winningTeamName) {
    this.winningTeamName = winningTeamName;
    return this;
  }

  @Override
  public Fixture set(String fieldName, Object value) {
    return (Fixture) super.set(fieldName, value);
  }

  @Override
  public Fixture clone() {
    return (Fixture) super.clone();
  }

}
