/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-26 at 19:15:37 UTC 
 * Modify at your own risk.
 */

package com.appspot.navestockcc_002.navestockccapi.model;

/**
 * Model definition for MatchReport.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the navestockccapi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MatchReport extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String createdby;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer matchId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String report;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer reportId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCreatedby() {
    return createdby;
  }

  /**
   * @param createdby createdby or {@code null} for none
   */
  public MatchReport setCreatedby(java.lang.String createdby) {
    this.createdby = createdby;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMatchId() {
    return matchId;
  }

  /**
   * @param matchId matchId or {@code null} for none
   */
  public MatchReport setMatchId(java.lang.Integer matchId) {
    this.matchId = matchId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getReport() {
    return report;
  }

  /**
   * @param report report or {@code null} for none
   */
  public MatchReport setReport(java.lang.String report) {
    this.report = report;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getReportId() {
    return reportId;
  }

  /**
   * @param reportId reportId or {@code null} for none
   */
  public MatchReport setReportId(java.lang.Integer reportId) {
    this.reportId = reportId;
    return this;
  }

  @Override
  public MatchReport set(String fieldName, Object value) {
    return (MatchReport) super.set(fieldName, value);
  }

  @Override
  public MatchReport clone() {
    return (MatchReport) super.clone();
  }

}
