/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-26 at 19:15:37 UTC 
 * Modify at your own risk.
 */

package com.appspot.navestockcc_002.navestockccapi.model;

/**
 * Model definition for ScoreCard.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the navestockccapi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ScoreCard extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer batingOrder;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String clubName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String firstname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String howOutDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer idClub;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer idHowOut;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer idMatch;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer idPlayer;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lastname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean objServiceDB;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer objServiceDBAction;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean objServiceSaved;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer oversBowled;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String player;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer runsConseded;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer runsScored;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer teamId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String teamName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer wickets;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getBatingOrder() {
    return batingOrder;
  }

  /**
   * @param batingOrder batingOrder or {@code null} for none
   */
  public ScoreCard setBatingOrder(java.lang.Integer batingOrder) {
    this.batingOrder = batingOrder;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getClubName() {
    return clubName;
  }

  /**
   * @param clubName clubName or {@code null} for none
   */
  public ScoreCard setClubName(java.lang.String clubName) {
    this.clubName = clubName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFirstname() {
    return firstname;
  }

  /**
   * @param firstname firstname or {@code null} for none
   */
  public ScoreCard setFirstname(java.lang.String firstname) {
    this.firstname = firstname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getHowOutDescription() {
    return howOutDescription;
  }

  /**
   * @param howOutDescription howOutDescription or {@code null} for none
   */
  public ScoreCard setHowOutDescription(java.lang.String howOutDescription) {
    this.howOutDescription = howOutDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIdClub() {
    return idClub;
  }

  /**
   * @param idClub idClub or {@code null} for none
   */
  public ScoreCard setIdClub(java.lang.Integer idClub) {
    this.idClub = idClub;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIdHowOut() {
    return idHowOut;
  }

  /**
   * @param idHowOut idHowOut or {@code null} for none
   */
  public ScoreCard setIdHowOut(java.lang.Integer idHowOut) {
    this.idHowOut = idHowOut;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIdMatch() {
    return idMatch;
  }

  /**
   * @param idMatch idMatch or {@code null} for none
   */
  public ScoreCard setIdMatch(java.lang.Integer idMatch) {
    this.idMatch = idMatch;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIdPlayer() {
    return idPlayer;
  }

  /**
   * @param idPlayer idPlayer or {@code null} for none
   */
  public ScoreCard setIdPlayer(java.lang.Integer idPlayer) {
    this.idPlayer = idPlayer;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLastname() {
    return lastname;
  }

  /**
   * @param lastname lastname or {@code null} for none
   */
  public ScoreCard setLastname(java.lang.String lastname) {
    this.lastname = lastname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getObjServiceDB() {
    return objServiceDB;
  }

  /**
   * @param objServiceDB objServiceDB or {@code null} for none
   */
  public ScoreCard setObjServiceDB(java.lang.Boolean objServiceDB) {
    this.objServiceDB = objServiceDB;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getObjServiceDBAction() {
    return objServiceDBAction;
  }

  /**
   * @param objServiceDBAction objServiceDBAction or {@code null} for none
   */
  public ScoreCard setObjServiceDBAction(java.lang.Integer objServiceDBAction) {
    this.objServiceDBAction = objServiceDBAction;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getObjServiceSaved() {
    return objServiceSaved;
  }

  /**
   * @param objServiceSaved objServiceSaved or {@code null} for none
   */
  public ScoreCard setObjServiceSaved(java.lang.Boolean objServiceSaved) {
    this.objServiceSaved = objServiceSaved;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getOversBowled() {
    return oversBowled;
  }

  /**
   * @param oversBowled oversBowled or {@code null} for none
   */
  public ScoreCard setOversBowled(java.lang.Integer oversBowled) {
    this.oversBowled = oversBowled;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPlayer() {
    return player;
  }

  /**
   * @param player player or {@code null} for none
   */
  public ScoreCard setPlayer(java.lang.String player) {
    this.player = player;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getRunsConseded() {
    return runsConseded;
  }

  /**
   * @param runsConseded runsConseded or {@code null} for none
   */
  public ScoreCard setRunsConseded(java.lang.Integer runsConseded) {
    this.runsConseded = runsConseded;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getRunsScored() {
    return runsScored;
  }

  /**
   * @param runsScored runsScored or {@code null} for none
   */
  public ScoreCard setRunsScored(java.lang.Integer runsScored) {
    this.runsScored = runsScored;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTeamId() {
    return teamId;
  }

  /**
   * @param teamId teamId or {@code null} for none
   */
  public ScoreCard setTeamId(java.lang.Integer teamId) {
    this.teamId = teamId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTeamName() {
    return teamName;
  }

  /**
   * @param teamName teamName or {@code null} for none
   */
  public ScoreCard setTeamName(java.lang.String teamName) {
    this.teamName = teamName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getWickets() {
    return wickets;
  }

  /**
   * @param wickets wickets or {@code null} for none
   */
  public ScoreCard setWickets(java.lang.Integer wickets) {
    this.wickets = wickets;
    return this;
  }

  @Override
  public ScoreCard set(String fieldName, Object value) {
    return (ScoreCard) super.set(fieldName, value);
  }

  @Override
  public ScoreCard clone() {
    return (ScoreCard) super.clone();
  }

}
